In [3]:
import pandas as pd

# 1. Cargar el archivo CSV
from google.colab import files
uploaded = files.upload()

# 2. Visualizar las primeras filas
import pandas as pd

datos = pd.read_csv('4_resultados_agua.csv')

datos.head()

Saving 4_resultados_agua.csv to 4_resultados_agua (1).csv

  Punto   Temp    pH  OD_promedio
0     A  22.25  7.15          6.2
1     B  24.30  7.20          5.8
2     C  19.80  6.85          4.9
3     D  23.65  7.05          6.5
4     E  25.15  7.25          5.0

In [4]:
# Identificar columnas
datos.columns

Index(['Punto', 'Temp', 'pH', 'OD_promedio'], dtype='object')

In [5]:
# Tipos de datos y estructura
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Punto        5 non-null      object
 1   Temp         5 non-null      float64
 2   pH           5 non-null      float64
 3   OD_promedio  5 non-null      float64
dtypes: float64(3), object(1)
memory usage: 292.0+ bytes

In [6]:
# Valores nulos
datos.isnull().sum()

Punto          0
Temp           0
pH             0
OD_promedio    0
dtype: int64

In [7]:
# Estadísticas descriptivas
datos.describe()

            Temp        pH  OD_promedio
count   5.000000  5.000000     5.000000
mean   23.030000  7.100000     5.680000
std     2.093621  0.158114     0.712039
min    19.800000  6.850000     4.900000
25%    22.250000  7.050000     5.000000
50%    23.650000  7.150000     5.800000
75%    24.300000  7.200000     6.200000
max    25.150000  7.250000     6.500000

## Análisis

Se reconocieron las columnas en el dataset, que corresponden a los distintos parámetros de la calidad del agua.

Por medio de la función info(), se analizaron la cantidad de registros y los tipos de datos, dando aval de observar la estructura del conjunto de datos.

Se examinaron los valores nulos por cada columna, esto es importante para reconocer posibles datos faltantes o inconsistencias.

Por último, se originaron estadísticas descriptivas que ayudan a comprender el comportamiento general de los datos, agregando valores promedio, mínimos y máximos.