In [3]:
from google.colab import files
files.upload()

Saving 4_resultados_agua.csv to 4_resultados_agua (1).csv

{'4_resultados_agua (1).csv': b'Punto,Temp,pH,OD_promedio\r\nA,22.25,7.15,6.2\r\nB,24.3,7.199999999999999,5.8\r\nC,19.8,6.85,4.9\r\nD,23.65,7.05,6.5\r\nE,25.15,7.25,5.0\r\n'}

In [4]:
import pandas as pd

df = pd.read_csv('4_resultados_agua.csv')
df.head()

  Punto   Temp    pH  OD_promedio
0     A  22.25  7.15          6.2
1     B  24.30  7.20          5.8
2     C  19.80  6.85          4.9
3     D  23.65  7.05          6.5
4     E  25.15  7.25          5.0

In [5]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Punto        5 non-null      object
 1   Temp         5 non-null      float64
 2   pH           5 non-null      float64
 3   OD_promedio  5 non-null      float64
dtypes: float64(3), object(1)
memory usage: 292.0+ bytes

            Temp        pH  OD_promedio
count   5.000000  5.000000     5.000000
mean   23.030000  7.100000     5.680000
std     2.093621  0.158114     0.712039
min    19.800000  6.850000     4.900000
25%    22.250000  7.050000     5.000000
50%    23.650000  7.150000     5.800000
75%    24.300000  7.200000     6.200000
max    25.150000  7.250000     6.500000

In [12]:
df['estado_pH'] = pd.cut(df['pH'], bins=[0,6.5,8.5,14], labels=['Ácido','Normal','Alcalino'])
df['estado_temp'] = pd.cut(df['Temp'], bins=[0,20,30,100], labels=['Baja','Normal','Alta'])
df['OD_promedio'] = pd.cut(df['OD_promedio'], bins=[0,5,8,20], labels=['Bajo','Aceptable','Óptimo'])

In [14]:
df['diagnostico'] = df['estado_ph'].astype(str) + ' - ' + \
                    df['estado_temp'].astype(str) + ' - ' + \
                    df['OD_promedio'].astype(str)

In [18]:
resumen = df[['pH', 'estado_temp', 'OD_promedio']].describe()
resumen

             pH
count  5.000000
mean   7.100000
std    0.158114
min    6.850000
25%    7.050000
50%    7.150000
75%    7.200000
max    7.250000

In [19]:
df['estado_ph'].value_counts()
df['estado_temp'].value_counts()
df['OD_promedio'].value_counts()

OD_promedio
Aceptable    3
Bajo         2
Óptimo       0
Name: count, dtype: int64

In [20]:
diagnostico_final = df.groupby('diagnostico').size().reset_index(name='conteo')
diagnostico_final

                   diagnostico  conteo
0         Normal - Baja - Bajo       1
1  Normal - Normal - Aceptable       3
2       Normal - Normal - Bajo       1

In [21]:
conclusion = diagnostico_final.sort_values(by='conteo', ascending=False)
conclusion.head(1)

                   diagnostico  conteo
1  Normal - Normal - Aceptable       3

In [23]:
df.to_csv('resultado_final_analisis.csv', index=False)

El respectivo análisis del parametro de pH, la temperatura y el oxígeno disuelto muestran una cierta condición predominante del agua el cual es el resultado más frecuente, lo que indica que la calidad del agua es tanto buena/moderada/crítica según los valores arrojados. Se recomienda un monitoreo continuo con el fin de poder mantener o mejorar las condiciones actuales.